#!/usr/bin/env bash
set -euo pipefail

OUT_DIR="${1:-/tmp/app-server-schema-out}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ACTIVE="$ROOT/SCHEMAS/app-server/active"

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

echo "[1/4] generate schema -> $OUT_DIR"
codex app-server generate-json-schema --out "$OUT_DIR"

echo "[2/4] replace active/json-schema"
rm -rf "$ACTIVE/json-schema"
mkdir -p "$ACTIVE"
cp -R "$OUT_DIR" "$ACTIVE/json-schema"

echo "[2.1/4] prune legacy schema artifacts"
bash "$ROOT/scripts/prune_schema_legacy.sh" "$ACTIVE/json-schema"

echo "[3/4] write metadata"
cat > "$ACTIVE/metadata.json" <<'JSON'
{
  "schemaName": "app-server",
  "generatedAtUtc": "REPLACE_ME",
  "generatorCommand": "codex app-server generate-json-schema --out <DIR>",
  "notes": "Schema update generated by scripts/update_schema.sh",
  "sourceOfTruth": "active/json-schema"
}
JSON

python3 - <<'PY'
import json
from datetime import datetime, timezone
from pathlib import Path

p = Path("SCHEMAS/app-server/active/metadata.json")
d = json.loads(p.read_text())
d["generatedAtUtc"] = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
p.write_text(json.dumps(d, indent=2, ensure_ascii=False) + "\n")
PY

echo "[4/4] generate manifest.sha256"
bash "$ROOT/scripts/write_schema_manifest.sh"

echo "DONE"
